# Generated by Django 4.2.5 on 2024-05-26 20:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(default='default@example.com', max_length=254, unique=True, verbose_name='endereço de email')),
                ('telefone', models.CharField(max_length=20)),
                ('categoria', models.CharField(choices=[('BIBLIOTECARIO', 'Bibliotecário'), ('AUTOR', 'Autor'), ('ADMIN', 'Administrador'), ('USUARIO', 'Usuário')], max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(auto_now_add=True)),
                ('data_devolucao_prevista', models.DateTimeField()),
                ('data_devolucao_realizada', models.DateTimeField(blank=True, null=True)),
                ('valor_total_emprestimo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDO', 'Concluído'), ('ATRASADO', 'Atrasado')], default='PENDENTE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('categoria', models.CharField(choices=[('EBOOK', 'E-book'), ('FISICO', 'Físico')], max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ano', models.PositiveIntegerField()),
                ('qtd_paginas', models.PositiveIntegerField()),
                ('numero_edicao', models.PositiveIntegerField()),
                ('descricao', models.TextField()),
                ('valor_emprestimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qtd_estoque', models.PositiveIntegerField()),
                ('estrelas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('imagem_capa', models.ImageField(upload_to='livros_capas/')),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('CANCELADO', 'Cancelado')], default='DISPONIVEL', max_length=20)),
                ('autorFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoriaFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuApp.categorialivro')),
                ('formatoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuApp.formato')),
                ('generoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuApp.genero')),
            ],
        ),
        migrations.CreateModel(
            name='itemEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emprestimoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuApp.emprestimo')),
                ('livroFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuApp.livro')),
            ],
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='livroFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuApp.livro'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='usuarioFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
