# Generated by Django 4.2.5 on 2024-05-26 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meuApp', '0002_foto_remove_livro_imagem_capa_livro_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='status',
        ),
    ]
