# Generated by Django 4.2.5 on 2024-05-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuApp', '0005_alter_livro_valor_emprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='valor_emprestimo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
